// Code generated by go-swagger; DO NOT EDIT.

package upload_s3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UploadS3OKCode is the HTTP code returned for type UploadS3OK
const UploadS3OKCode int = 200

/*UploadS3OK OK

swagger:response uploadS3OK
*/
type UploadS3OK struct {
}

// NewUploadS3OK creates UploadS3OK with default headers values
func NewUploadS3OK() *UploadS3OK {

	return &UploadS3OK{}
}

// WriteResponse to the client
func (o *UploadS3OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
