// Code generated by go-swagger; DO NOT EDIT.

package default_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DefaultOKCode is the HTTP code returned for type DefaultOK
const DefaultOKCode int = 200

/*DefaultOK OK

swagger:response defaultOK
*/
type DefaultOK struct {
}

// NewDefaultOK creates DefaultOK with default headers values
func NewDefaultOK() *DefaultOK {

	return &DefaultOK{}
}

// WriteResponse to the client
func (o *DefaultOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
